<?php

/**
 * Implements hook_theme().
 */
function landing_module_theme($existing, $type, $theme, $path)
{
    return [
        'nav_bar_template' => [
            'variables' => [
                'value' => NULL,
                'landingIsActive' => false,
            ],
        ],
        'landing_module_template' => [
            'variables' => [
                'comments' => NULL,
                'benefits' => NULL
            ]
        ],
        'person_form_template' => [
            'variables' => [
                'title' => NULL,
                'paragraph' => NULL
            ]
        ],
        'city_background_template' => [
            'variables' => []
        ],
        'resume_template' => [
            'variables' => [
                'name' => NULL,
                'documentType' => NULL,
                'documentNumber' => NULL,
                'genre' => NULL,
                'age' => NULL,
                'vehicle_plate' => NULL,
            ]
        ],
        'footer_template' => [
            'variables' => [
                'body' => NULL,
                'comments' => NULL,
                'benefits' => NULL
            ]
        ]
    ];
}
